apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: microservices-demo

build:
  local:
    push: false
    concurrency: 3
  artifacts:
    - image: api-gateway
      context: api-gateway
      custom:
        buildCommand: cd $BUILD_CONTEXT && ./gradlew bootJar -x test && docker build -f Dockerfile.slim -t $IMAGE .
        dependencies:
          paths: [src, build.gradle, settings.gradle, gradle, k8s]
    - image: order-service
      context: order-service
      custom:
        buildCommand: cd $BUILD_CONTEXT && ./gradlew bootJar -x test && docker build -f Dockerfile.slim -t $IMAGE .
        dependencies:
          paths: [src, build.gradle, settings.gradle, gradle, k8s]
    - image: inventory-service
      context: inventory-service
      custom:
        buildCommand: cd $BUILD_CONTEXT && ./gradlew bootJar -x test && docker build -f Dockerfile.slim -t $IMAGE .
        dependencies:
          paths: [src, build.gradle, settings.gradle, gradle, k8s]

manifests:
  rawYaml:
    - k8s/namespace.yaml
    - k8s/postgres.yaml
    - k8s/redis.yaml
    - k8s/kafka.yaml
    - k8s/zipkin.yaml
    - k8s/keycloak.yaml
    - api-gateway/k8s/serviceaccount.yaml
    - api-gateway/k8s/configmap.yaml
    - api-gateway/k8s/secret.yaml
    - api-gateway/k8s/deployment.yaml
    - api-gateway/k8s/service.yaml
    - order-service/k8s/serviceaccount.yaml
    - order-service/k8s/configmap.yaml
    - order-service/k8s/secret.yaml
    - order-service/k8s/deployment.yaml
    - order-service/k8s/service.yaml
    - inventory-service/k8s/serviceaccount.yaml
    - inventory-service/k8s/configmap.yaml
    - inventory-service/k8s/secret.yaml
    - inventory-service/k8s/deployment.yaml
    - inventory-service/k8s/service.yaml

deploy:
  kubectl: { }

profiles:
  - name: infra-only
    manifests:
      rawYaml:
        - k8s/namespace.yaml
        - k8s/postgres.yaml
        - k8s/redis.yaml
        - k8s/kafka.yaml
        - k8s/zipkin.yaml
        - k8s/keycloak.yaml

  - name: services-only
    manifests:
      rawYaml:
        - api-gateway/k8s/serviceaccount.yaml
        - api-gateway/k8s/configmap.yaml
        - api-gateway/k8s/secret.yaml
        - api-gateway/k8s/deployment.yaml
        - api-gateway/k8s/service.yaml
        - order-service/k8s/serviceaccount.yaml
        - order-service/k8s/configmap.yaml
        - order-service/k8s/secret.yaml
        - order-service/k8s/deployment.yaml
        - order-service/k8s/service.yaml
#        - inventory-service/k8s/serviceaccount.yaml
#        - inventory-service/k8s/configmap.yaml
#        - inventory-service/k8s/secret.yaml
#        - inventory-service/k8s/deployment.yaml
#        - inventory-service/k8s/service.yaml