server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: false
      config:
        enabled: false
    gateway:
      server:
        webflux:
          routes:
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/orders/**
              filters:
                - AddRequestHeader=X-Source, api-gateway

            - id: inventory-service
              uri: lb://inventory-service
              predicates:
                - Path=/api/inventory/**
              filters:
                - AddRequestHeader=X-Source, api-gateway

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

logging:
  level:
    uz.coder: DEBUG
    org.springframework.cloud.gateway: INFO