apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service
  namespace: microservices
  labels:
    app: order-service
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "orders"
  DB_USERNAME: "postgres"
  SPRING_PROFILES_ACTIVE: "kubernetes"
  KEYCLOAK_ISSUER_URI: "http://keycloak:8080/realms/microservices"