apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: microservices
  labels:
    app: order-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8081"
    spec:
      serviceAccountName: order-service-sa
      containers:
        - name: order-service
          image: order-service
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8081
            - name: grpc
              containerPort: 9090
          envFrom:
            - configMapRef:
                name: order-service
            - secretRef:
                name: order-service-secret
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          startupProbe:
            httpGet:
              path: /api/orders/actuator/health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 13
          readinessProbe:
            httpGet:
              path: /api/orders/actuator/health/readiness
              port: 8081
            initialDelaySeconds: 0
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/orders/actuator/health/liveness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3