apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service-sa
  namespace: microservices
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: order-service-role
rules:
  - apiGroups: [""]
    resources: [configmaps, pods, services, endpoints, namespaces, secrets]
    verbs: [get, watch, list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: order-service-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: order-service-role
subjects:
  - kind: ServiceAccount
    name: order-service-sa
    namespace: microservices