server:
  port: 8081
  servlet:
    context-path: /api/orders

spring:
  application:
    name: order-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/microservices}

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:orders}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 5
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:redisPass}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,prometheus
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true

inventory:
  service:
    url: ${INVENTORY_SERVICE_URL:http://inventory-service:8082}

grpc:
  server:
    port: 9090
  client:
    inventory-service:
      address: static://inventory-service:9090
      negotiation-type: plaintext

resilience4j:
  circuitbreaker:
    instances:
      inventory:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
      inventory-broken:
        slidingWindowSize: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 1
        registerHealthIndicator: true
      inventory-annotation:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
      inventory-annotation-broken:
        slidingWindowSize: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 1
        registerHealthIndicator: true

logging:
  level:
    uz.coder: DEBUG