apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway
  namespace: microservices
  labels:
    app: api-gateway
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  KEYCLOAK_ISSUER_URI: "http://keycloak:8080/realms/microservices"