apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-service
  namespace: microservices
  labels:
    app: inventory-service
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "inventory"
  DB_USERNAME: "postgres"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  ZIPKIN_ENDPOINT: "http://zipkin:9411/api/v2/spans"
  JWT_ISSUER_URI: "http://keycloak:8080/realms/microservices"
  JWT_JWK_SET_URI: "http://keycloak:8080/realms/microservices/protocol/openid-connect/certs"
  SPRING_PROFILES_ACTIVE: "kubernetes"