apiVersion: v1
kind: Secret
metadata:
  name: inventory-service-secret
  namespace: microservices
  labels:
    app: inventory-service
type: Opaque
stringData:
  DB_PASSWORD: "dbPass"
  REDIS_PASSWORD: "redisPass"